apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karakeep
  name: karakeep
  namespace: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep
  template:
    metadata:
      labels:
        app: karakeep
    spec:
      hostname: karakeep
      volumes:
        - name: karakeep-app
          hostPath:
            path: /mnt/data/karakeep/app
            type: DirectoryOrCreate
        - name: karakeep-meilisearch
          hostPath:
            path: /mnt/data/karakeep/meilisearch
            type: DirectoryOrCreate
      containers:
        - name: karakeep-app
          image: ghcr.io/karakeep-app/karakeep:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: karakeep-generic-configmap
            - secretRef:
                name: karakeep-generic-secrets
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: karakeep-app
              mountPath: /data
          resources: {}
        - name: karakeep-chrome
          image: gcr.io/zenika-hub/alpine-chrome:latest
          imagePullPolicy: Always
          args: 
            - --no-sandbox
            - --disable-gpu
            - --disable-dev-shm-usage
            - --remote-debugging-address=0.0.0.0
            - --remote-debugging-port=9222
            - --hide-scrollbars
          envFrom:
            - configMapRef:
                name: karakeep-generic-configmap
            - secretRef:
                name: karakeep-generic-secrets
          ports:
            - containerPort: 9222
          resources: {}
        - name: karakeep-meilisearch
          image: getmeili/meilisearch:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: karakeep-generic-configmap
            - secretRef:
                name: karakeep-generic-secrets
          ports:
            - containerPort: 7700
          volumeMounts:
            - name: karakeep-meilisearch
              mountPath: /meili_data
          resources: {}